"""Add triggered_at to Alert model

Revision ID: 0c30e8b91779
Revises: da56255ba4b3
Create Date: 2026-09-26 21:01:52.658753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c30e8b91779'
down_revision = 'da56255ba4b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.add_column(sa.Column('triggered_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.drop_column('triggered_at')

    # ### end Alembic commands ###
