"""Add company_name, exchange, currency to Watchlist

Revision ID: 45e6f139340f
Revises: 45a474b7beb2
Create Date: 2026-09-25 21:06:08.077870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45e6f139340f'
down_revision = '45a474b7beb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('exchange', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.drop_column('currency')
        batch_op.drop_column('exchange')
        batch_op.drop_column('company_name')
    # ### end Alembic commands ###
