"""Add StockCache model

Revision ID: 6bbe70e5b18e
Revises: 0a6b4c86635b
Create Date: 2026-09-27 20:51:34.451529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bbe70e5b18e'
down_revision = '0a6b4c86635b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=True),
    sa.Column('exchange', sa.String(length=20), nullable=True),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=30, scale=2), nullable=True),
    sa.Column('pe_ratio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_cache_exchange'), ['exchange'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_cache_market_cap'), ['market_cap'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_cache_pe_ratio'), ['pe_ratio'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_cache_sector'), ['sector'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_cache_symbol'), ['symbol'], unique=True)
        batch_op.create_index(batch_op.f('ix_stock_cache_volume'), ['volume'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_cache_volume'))
        batch_op.drop_index(batch_op.f('ix_stock_cache_symbol'))
        batch_op.drop_index(batch_op.f('ix_stock_cache_sector'))
        batch_op.drop_index(batch_op.f('ix_stock_cache_pe_ratio'))
        batch_op.drop_index(batch_op.f('ix_stock_cache_market_cap'))
        batch_op.drop_index(batch_op.f('ix_stock_cache_exchange'))

    op.drop_table('stock_cache')
    # ### end Alembic commands ###
