"""Add CMSContent

Revision ID: d0212d3083e6
Revises: 2e28cdaa78d3
Create Date: 2026-09-28 10:38:29.759223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0212d3083e6'
down_revision = '2e28cdaa78d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cms_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cms_content', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cms_content_key'), ['key'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cms_content', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cms_content_key'))

    op.drop_table('cms_content')
    # ### end Alembic commands ###
